
# Singleton service factory configuration/IoC injection
singletons:
- com.networknt.registry.URL:
    - com.networknt.registry.URLImpl:
        protocol: https
        host: localhost
        port: 8080
        path: direct
        parameters:
          com.networknt.portal.hybrid.query-1.0.0: http://localhost:8080?environment=dev
- com.networknt.registry.Registry:
    - com.networknt.registry.support.DirectRegistry
- com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - com.networknt.rpc.router.RpcRouter
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  # registry all service handlers by from annotations
  - com.networknt.rpc.router.RpcStartupHookProvider
  # User Query Startup Hook
  - net.lightapi.portal.user.query.UserQueryStartup
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  # User Query Shutdown Hook
  - net.lightapi.portal.user.query.UserQueryShutdown

